name: iaf

dependencies:
        - python=2.7
        - ipython
        - six
        - matplotlib
        - jupyter
        - PIL

        - pip:
                - https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.11.0-cp27-none-linux_x86_64.whl
                - numpy==1.11.0
                - Theano==0.8.2
                - tqdm
                - sacred
